import { useMemo } from 'react';
import {
  buildLibraryMusicContextValue,
  buildMiniPlayerMusicContextValue,
  buildNowPlayingMusicContextValue,
} from './musicContextValues';
import type {
  LibraryMusicContextValue,
  MiniPlayerMusicContextValue,
  MusicContextValue,
  NowPlayingMusicContextValue,
} from './musicContextTypes';

interface ProvidedMusicContextValues {
  value: MusicContextValue;
  libraryValue: LibraryMusicContextValue;
  miniPlayerValue: MiniPlayerMusicContextValue;
  nowPlayingValue: NowPlayingMusicContextValue;
}

export const useProvidedMusicContextValues = ({
  songs,
  setSongs,
  addSongs,
  updateSongMetadata,
  currentSong,
  playbackQueue,
  isPlaying,
  isBuffering,
  playSong,
  togglePlayPause,
  stop,
  seekTo,
  next,
  previous,
  shuffle,
  toggleShuffle,
  repeatMode,
  cycleRepeatMode,
  volume,
  setVolume,
  eqEnabled,
  setEqEnabled,
  eqBands,
  setEqBand,
  eqPreset,
  applyEqPreset,
  eqNative,
  fftBins,
  visualizerRunning,
  visualizerError,
  palette,
  playlists,
  createPlaylist,
  deletePlaylist,
  renamePlaylist,
  addSongToPlaylist,
  removeSongFromPlaylist,
  playPlaylist,
  isReady,
}: MusicContextValue): ProvidedMusicContextValues => {
  const value = useMemo<MusicContextValue>(
    () => ({
      songs,
      setSongs,
      addSongs,
      updateSongMetadata,
      currentSong,
      playbackQueue,
      isPlaying,
      isBuffering,
      playSong,
      togglePlayPause,
      stop,
      seekTo,
      next,
      previous,
      shuffle,
      toggleShuffle,
      repeatMode,
      cycleRepeatMode,
      volume,
      setVolume,
      eqEnabled,
      setEqEnabled,
      eqBands,
      setEqBand,
      eqPreset,
      applyEqPreset,
      eqNative,
      fftBins,
      visualizerRunning,
      visualizerError,
      palette,
      playlists,
      createPlaylist,
      deletePlaylist,
      renamePlaylist,
      addSongToPlaylist,
      removeSongFromPlaylist,
      playPlaylist,
      isReady,
    }),
    [
      songs,
      setSongs,
      addSongs,
      updateSongMetadata,
      currentSong,
      playbackQueue,
      isPlaying,
      isBuffering,
      playSong,
      togglePlayPause,
      stop,
      seekTo,
      next,
      previous,
      shuffle,
      toggleShuffle,
      repeatMode,
      cycleRepeatMode,
      volume,
      setVolume,
      eqEnabled,
      setEqEnabled,
      eqBands,
      setEqBand,
      eqPreset,
      applyEqPreset,
      eqNative,
      fftBins,
      visualizerRunning,
      visualizerError,
      palette,
      playlists,
      createPlaylist,
      deletePlaylist,
      renamePlaylist,
      addSongToPlaylist,
      removeSongFromPlaylist,
      playPlaylist,
      isReady,
    ],
  );

  const libraryValue = useMemo(
    () => buildLibraryMusicContextValue(value),
    [value],
  );

  const miniPlayerValue = useMemo(
    () => buildMiniPlayerMusicContextValue(value),
    [value],
  );

  const nowPlayingValue = useMemo(
    () => buildNowPlayingMusicContextValue(value),
    [value],
  );

  return { value, libraryValue, miniPlayerValue, nowPlayingValue };
};